# Generated by Django 3.1.2 on 2020-11-01 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="post_user_dislikes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Who dislike post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="post_user_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Who like post",
            ),
        ),
    ]
